---
title: "Test_GitBash"
author: "Gabriela Palomo"
output: html_document
---

### How to add an existing project to GitHub using Git Bash

1. Make sure your RStudio command shell is set to be Git Bash. 

2. Make a new repository in your GitHub account. 

3. Copy the remote repository URL from your GitHub project. 

4. Open your project in RStudio. Remember this is an old project you´ve never linked to GitHub before. 

5. Open Git Bash. 

6. Change the directory to to your project´s directory. In this case I did the following. cd means change directory. And always start with a / before the C. 

$ cd /C/Users/Bella/Documents/R/Test_GitBash

7. Now initialize the local directory as a Git repository. 

$ git init

8. Add the files to your new local repository. This will allow them to be committed as the "First Commit". Don´t forget the . at the end

$ git add .

9. Now create your first commit message. 

$ git commit -m "First commit"

10. Add the URL from your GitHub repository.

$ git remote add origin https://github.com/GabsPalomo/Test_GitBash.git

11. Verify the new remote URL

$ git remote -v

12. Push the changes you made on your local repository to your remote repository on GitHub. This is your first push. That will record origin/master as a remote tracking branch, and will enable the next push to automatically push master to origin/master.

$ git push -u origin master

13. Then you can use

$ git checkout master

or to push

$ git push